# Movielens download

1. download MovieLens 1M public dataset
2. Write datasets to TF-Records
3. Generate dataset vocabulary and look-up dictionaries

## imports

In [1]:
import sys
sys.path.append("..")
import env_config

In [2]:
print(f"PREFIX: {env_config.PREFIX}")
print(f"PROJECT_ID: {env_config.PROJECT_ID}")
print(f"LOCATION: {env_config.LOCATION}")

PREFIX: jt-towers-v1
PROJECT_ID: hybrid-vertex
LOCATION: us-central1

In [3]:
!pwd

/home/jupyter/crispy_towers/notebooks

In [5]:
import os
import json
from pprint import pprint
import pickle as pkl
import numpy as np
import pandas as pd

import logging
logging.disable(logging.WARNING)
import warnings
warnings.filterwarnings('ignore')

# tensorflow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import tensorflow_datasets as tfds

# google cloud
from google.cloud import aiplatform, storage

# cloud storage client
storage_client = storage.Client(project=env_config.PROJECT_ID)
# bucket = storage_client.bucket(BUCKET_NAME)

# Vertex client
aiplatform.init(project=env_config.PROJECT_ID, location=env_config.LOCATION)

sys.path.append("..")
from src.data import data_utils as data_utils

## config: data download and prep

In [6]:
LOCAL_OUTPUT_DIR     = "local_data/examples"
LOCAL_EXTRACT_DIR    = "local_data/raw"

MIN_TIMELINE_LENGTH  = 3
MIN_RATING           = 1

NUM_TRAIN_RECORDS    = 8
NUM_VAL_RECORDS      = 3

BUILD_VOCAB          = True

print(f"EXAMPLE_GEN_GCS_PATH : {env_config.EXAMPLE_GEN_GCS_PATH}")
print(f"TF_RECORD_PREFIX     : {env_config.TF_RECORD_PREFIX}")
print(f"MAX_CONTEXT_LENGTH   : {env_config.MAX_CONTEXT_LENGTH}")
print(f"MAX_GENRE_LENGTH     : {env_config.MAX_GENRE_LENGTH}")

EXAMPLE_GEN_GCS_PATH : data/movielens/m1m
TF_RECORD_PREFIX     : ml1m
MAX_CONTEXT_LENGTH   : 10
MAX_GENRE_LENGTH     : 10

#### create GCS bucket

In [7]:
REGION=env_config.LOCATION
BUCKET_URI=f"gs://{env_config.BUCKET_NAME}"

In [13]:
!gsutil mb -l $REGION $BUCKET_URI

Creating gs://jt-towers-v1-hybrid-vertex-bucket/...

### copy these commands to command line terminal

In [8]:
print("copy these commands into terminal:\n")
print(f"export PROJECT_ID={env_config.PROJECT_ID}")
print(f"export BUCKET_NAME={env_config.BUCKET_NAME}")
print(f"export EXAMPLE_GEN_GCS_PATH={env_config.EXAMPLE_GEN_GCS_PATH}")
print(f"export TF_RECORD_PREFIX={env_config.TF_RECORD_PREFIX}")
print(f"export MAX_GENRE_LENGTH={env_config.MAX_GENRE_LENGTH}")
print(f"export MAX_CONTEXT_LENGTH={env_config.MAX_CONTEXT_LENGTH}")
print(f"export LOCAL_EXTRACT_DIR={LOCAL_EXTRACT_DIR}")
print(f"export LOCAL_OUTPUT_DIR={LOCAL_OUTPUT_DIR}")
print(f"export MIN_TIMELINE_LENGTH={MIN_TIMELINE_LENGTH}")
print(f"export MIN_RATING={MIN_RATING}")
print(f"export BUILD_VOCAB={BUILD_VOCAB}")
print(f"export NUM_TRAIN_RECORDS={NUM_TRAIN_RECORDS}")
print(f"export NUM_VAL_RECORDS={NUM_VAL_RECORDS}")
print(f"chmod +x example_gen_movielens.py")

copy these commands into terminal:

export PROJECT_ID=hybrid-vertex
export BUCKET_NAME=jt-towers-v1-hybrid-vertex-bucket
export EXAMPLE_GEN_GCS_PATH=data/movielens/m1m
export TF_RECORD_PREFIX=ml1m
export MAX_GENRE_LENGTH=10
export MAX_CONTEXT_LENGTH=10
export LOCAL_EXTRACT_DIR=local_data/raw
export LOCAL_OUTPUT_DIR=local_data/examples
export MIN_TIMELINE_LENGTH=3
export MIN_RATING=1
export BUILD_VOCAB=True
export NUM_TRAIN_RECORDS=8
export NUM_VAL_RECORDS=3
chmod +x example_gen_movielens.py

In [15]:
data_gen_command = """python example_gen_movielens.py --project_id=$PROJECT_ID --gcs_bucket_name=$BUCKET_NAME \
--gcs_data_path_prefix=$EXAMPLE_GEN_GCS_PATH \
--tfrecord_prefix=$TF_RECORD_PREFIX \
--local_data_dir=$LOCAL_EXTRACT_DIR \
--local_output_dir=$LOCAL_OUTPUT_DIR \
--min_timeline_length=$MIN_TIMELINE_LENGTH \
--max_context_length=$MAX_CONTEXT_LENGTH \
--max_context_movie_genre_length=$MAX_GENRE_LENGTH \
--min_rating=$MIN_RATING \
--train_data_fraction=0.9 \
--build_vocabs=$BUILD_VOCAB \
--num_train_tfrecords=$NUM_TRAIN_RECORDS \
--num_test_tfrecords=$NUM_VAL_RECORDS \
"""
print(data_gen_command)

python example_gen_movielens.py --project_id=$PROJECT_ID --gcs_bucket_name=$BUCKET_NAME --gcs_data_path_prefix=$EXAMPLE_GEN_GCS_PATH --tfrecord_prefix=$TF_RECORD_PREFIX --local_data_dir=$LOCAL_EXTRACT_DIR --local_output_dir=$LOCAL_OUTPUT_DIR --min_timeline_length=$MIN_TIMELINE_LENGTH --max_context_length=$MAX_CONTEXT_LENGTH --max_context_movie_genre_length=$MAX_GENRE_LENGTH --min_rating=$MIN_RATING --train_data_fraction=0.9 --build_vocabs=$BUILD_VOCAB --num_train_tfrecords=$NUM_TRAIN_RECORDS --num_test_tfrecords=$NUM_VAL_RECORDS

# Confim tfrecords

In [9]:
GCS_DATA_PATH = f"{env_config.BUCKET_URI}/{env_config.EXAMPLE_GEN_GCS_PATH}"
print(f"GCS_DATA_PATH : {GCS_DATA_PATH}")

! gsutil ls $GCS_DATA_PATH

GCS_DATA_PATH : gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m
gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/
gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/val/
gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/vocabs/

In [10]:
all_files = []
for blob in storage_client.list_blobs(
    f"{env_config.BUCKET_NAME}", 
    prefix=f'{env_config.EXAMPLE_GEN_GCS_PATH}/train/', 
    # delimiter='/'
):
    if '.tfrecord' in blob.name:
        all_files.append(blob.public_url.replace("https://storage.googleapis.com/", "gs://"))
        
all_files

['gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-001-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-002-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-003-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-004-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-005-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-006-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-007-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-008-of-008.tfrecord']

In [11]:
for blob in storage_client.list_blobs(
    f"{env_config.BUCKET_NAME}", 
    prefix=f'{env_config.EXAMPLE_GEN_GCS_PATH}/val/', 
    # delimiter='/'
):
    if '.tfrecord' in blob.name:
        all_files.append(blob.public_url.replace("https://storage.googleapis.com/", "gs://"))
        
all_files

['gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-001-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-002-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-003-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-004-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-005-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-006-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-007-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/train/ml1m-008-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/val/ml1m-001-of-003.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/val/ml1m-002-of-003.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/val/ml1m-003-of-003.tfrecord']

In [13]:
mv_dataset = tf.data.TFRecordDataset(all_files)
# train_dataset = train_dataset.map(movielens_ds_utils.parse_tfrecord)
mv_dataset = mv_dataset.map(data_utils._parse_function)

for x in mv_dataset.batch(1).take(1):
    pprint(x)

{'context_movie_genre': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'Animation', b'Comedy', b'Thriller', b'Animation',
        b"Children's", b'Comedy', b'Musical', b'Animation',
        b"Children's", b'Comedy']], dtype=object)>,
 'context_movie_id': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'735', b'2009', b'2012', b'2965', b'3682', b'907', b'1268',
        b'2231', b'887', b'902']], dtype=object)>,
 'context_movie_rating': <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[5., 4., 3., 2., 4., 3., 5., 4., 3., 4.]], dtype=float32)>,
 'context_movie_title': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'Close Shave, A (1995)', b'Jungle Book, The (1967)',
        b'Little Mermaid, The (1989)', b'Robin Hood (1973)',
        b'Chicken Run (2000)', b'Wizard of Oz, The (1939)',
        b'This Is Spinal Tap (1984)', b'Producers, The (1968)',
        b"Singin' in the Rain (1952)", b'My Fair Lady (1964)']],
      dtype=object)>,
 'context_movie_year': <tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[1995, 1967, 1989, 1973, 2000, 1939, 1984, 1968, 1952, 1964]])>,
 'context_rating_timestamp': <tf.Tensor: shape=(1, 10), dtype=int64, numpy=
array([[962569921, 962569966, 962569966, 962569966, 962569966, 962570076,
        962570076, 962570076, 962570076, 962570099]])>,
 'target_movie_genres': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b"Children's", b'Comedy', b'Musical', b'UNK', b'UNK', b'UNK',
        b'UNK', b'UNK', b'UNK', b'UNK']], dtype=object)>,
 'target_movie_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'1015'], dtype=object)>,
 'target_movie_rating': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([3.], dtype=float32)>,
 'target_movie_title': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Mary Poppins (1964)'], dtype=object)>,
 'target_movie_year': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1964])>,
 'target_rating_timestamp': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([962570100])>,
 'user_age': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([25])>,
 'user_gender': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'M'], dtype=object)>,
 'user_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'5027'], dtype=object)>,
 'user_occupation_text': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'programmer'], dtype=object)>,
 'user_zip_code': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'92404'], dtype=object)>}

# Validate vocab file

In [14]:
VOCAB_FILENAME="vocab_dict.pkl"

In [15]:
EXISTING_VOCAB_FILE = f'gs://{env_config.BUCKET_NAME}/{env_config.EXAMPLE_GEN_GCS_PATH}/vocabs/{VOCAB_FILENAME}'
print(f"Downloading vocab...")

os.system(f'gsutil -q cp {EXISTING_VOCAB_FILE} .')
print(f"Downloaded vocab from: {EXISTING_VOCAB_FILE}\n")

filehandler = open(VOCAB_FILENAME, 'rb')
vocab_dict = pkl.load(filehandler)
filehandler.close()

for key in vocab_dict.keys():
    pprint(key)

Downloading vocab...
Downloaded vocab from: gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m/vocabs/vocab_dict.pkl

'movie_id'
'movie_year'
'movie_genre'
'movie_title'
'user_id'
'user_gender_vocab'
'user_age_vocab'
'user_occ_vocab'
'user_zip_vocab'
'min_timestamp'
'max_timestamp'
'timestamp_buckets'

In [25]:
list_of_years = vocab_dict['movie_year'] #.tolist()

min_yr = min(list_of_years)
max_yr = max(list_of_years)

print(f"min: {min_yr}; max: {max_yr}")

min: 0; max: 2000

In [16]:
MOVIELENS_NUM_MOVIES = len(vocab_dict['movie_id'])
MOVIELENS_NUM_USERS = len(vocab_dict['user_id'])

print(f"MOVIELENS_NUM_MOVIES : {MOVIELENS_NUM_MOVIES}")
print(f"MOVIELENS_NUM_USERS  : {MOVIELENS_NUM_USERS}")

MOVIELENS_NUM_MOVIES : 3884
MOVIELENS_NUM_USERS  : 6041

# Create look-up dictionaries

In [23]:
USER_AGE_LOOKUP = data_utils.get_dictionary_lookup_by_tf_data_key(
    key = 'user_age'
    , dataset = mv_dataset
)

USER_AGE_DIM = len(USER_AGE_LOOKUP)
print(f"USER_AGE_DIM: {USER_AGE_DIM}")


USER_OCC_LOOKUP = data_utils.get_dictionary_lookup_by_tf_data_key(
    key = 'user_occupation_text'
    , dataset= mv_dataset
)
USER_OCC_LOOKUP[b''] = 21
USER_OCC_DIM = len(USER_OCC_LOOKUP)
print(f"USER_OCC_DIM: {USER_OCC_DIM}")

USER_AGE_DIM: 8
USER_OCC_DIM: 22

In [24]:
config = f'''
USER_AGE_LOOKUP       = {USER_AGE_LOOKUP}
USER_AGE_DIM          = {USER_AGE_DIM}
USER_OCC_LOOKUP       = {USER_OCC_LOOKUP}
USER_OCC_DIM          = {USER_OCC_DIM}
MOVIELENS_NUM_MOVIES  = {MOVIELENS_NUM_MOVIES}
MOVIELENS_NUM_USERS   = {MOVIELENS_NUM_USERS}
'''
    
with open(f'../src/data/mv_lookup_dicts.py', 'w') as f:
    f.write(config)

In [33]:
df_all = tfds.as_dataframe(mv_dataset.take(20))
df_all.head(5)

,context_movie_genre,context_movie_id,context_movie_rating,context_movie_title,context_movie_year,context_rating_timestamp,target_movie_genres,target_movie_id,target_movie_rating,target_movie_title,target_movie_year,target_rating_timestamp,user_age,user_gender,user_id,user_occupation_text,user_zip_code
0,"[b'Animation', b'Comedy', b'Thriller', b'Anima...","[b'735', b'2009', b'2012', b'2965', b'3682', b...","[5.0, 4.0, 3.0, 2.0, 4.0, 3.0, 5.0, 4.0, 3.0, ...","[b'Close Shave, A (1995)', b'Jungle Book, The ...","[1995, 1967, 1989, 1973, 2000, 1939, 1984, 196...","[962569921, 962569966, 962569966, 962569966, 9...","[b""Children's"", b'Comedy', b'Musical', b'UNK',...",b'1015',3.0,b'Mary Poppins (1964)',1964,962570100,25,b'M',b'5027',b'programmer',b'92404'
1,"[b'Drama', b'War', b'Drama', b'Comedy', b'Dram...","[b'40', b'1170', b'1223', b'3599', b'2993', b'...","[4.0, 3.0, 3.0, 4.0, 4.0, 2.0, 2.0, 3.0, 5.0, ...","[b'Richard III (1995)', b'Passion Fish (1992)'...","[1995, 1992, 1990, 1968, 1962, 1992, 1980, 198...","[965267494, 965267527, 965267527, 965267527, 9...","[b'Drama', b'UNK', b'UNK', b'UNK', b'UNK', b'U...",b'148',5.0,b'Apollo 13 (1995)',1995,965267578,25,b'M',b'4302',b'artist',b'91910'
2,"[b'Horror', b'Drama', b'UNK', b'UNK', b'UNK', ...","[b'2390', b'1104', b'0', b'0', b'0', b'0', b'0...","[4.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[b'Texas Chainsaw Massacre, The (1974)', b'Peo...","[1974, 1996, 0, 0, 0, 0, 0, 0, 0, 0]","[975796636, 975796636, 0, 0, 0, 0, 0, 0, 0, 0]","[b'Comedy', b'UNK', b'UNK', b'UNK', b'UNK', b'...",b'859',1.0,"b""Gone Fishin' (1997)""",1997,975796636,18,b'M',b'620',b'college/grad student',b'93560'
3,"[b'Drama', b'Romance', b'Drama', b'Comedy', b'...","[b'890', b'1282', b'1061', b'2484', b'1202', b...","[4.0, 3.0, 3.0, 3.0, 4.0, 4.0, 5.0, 0.0, 0.0, ...","[b""Breakfast at Tiffany's (1961)"", b'Field of ...","[1961, 1989, 1973, 1960, 1980, 1982, 1977, 0, ...","[965524610, 965524610, 965524610, 965524646, 9...","[b'Horror', b'UNK', b'UNK', b'UNK', b'UNK', b'...",b'2949',3.0,b'Re-Animator (1985)',1985,965612488,35,b'M',b'4018',b'technician/engineer',b'54601'
4,"[b'Comedy', b'Drama', b'Comedy', b'Thriller', ...","[b'367', b'1434', b'2734', b'2226', b'365', b'...","[3.0, 3.0, 4.0, 4.0, 3.0, 3.0, 1.0, 3.0, 1.0, ...","[b'Paper, The (1994)', b'Vegas Vacation (1997)...","[1994, 1997, 1993, 1998, 1994, 1995, 1999, 199...","[974614949, 974615030, 974615030, 974615067, 9...","[b'Thriller', b'UNK', b'UNK', b'UNK', b'UNK', ...",b'3150',4.0,b'Pacific Heights (1990)',1990,974615327,50,b'M',b'2172',b'retired',b'87502'

# Create parsed candidate dataset

> for help, see [Load data from DataFrame](https://cloud.google.com/bigquery/docs/samples/bigquery-load-table-dataframe#code-sample) from BigQuery code samples

### from tfds

In [304]:
# movies_tfds = tfds.load("movielens/100k-movies", split="train")

for x in movies_tfds.take(1).as_numpy_iterator():
    pprint(x)

{'movie_genres': array([4]),
 'movie_id': b'1681',
 'movie_title': b'You So Crazy (1994)'}

### from downloaded TF dataset

##### tmp - debugging: START

> see [this example](https://stackoverflow.com/questions/26886653/create-new-column-based-on-values-from-other-columns-apply-a-function-of-multi)

In [607]:
# def label_race(row):
#     if row['eri_hispanic'] == 1:
#         return 'Hispanic'
#     if row['eri_afr_amer'] + row['eri_asian'] + row['eri_hawaiian'] + row['eri_nat_amer'] + row['eri_white'] > 1:
#         return 'Two Or More'
#     if row['eri_nat_amer'] == 1:
#         return 'A/I AK Native'
#     if row['eri_asian'] == 1:
#         return 'Asian'
#     if row['eri_afr_amer'] == 1:
#         return 'Black/AA'
#     if row['eri_hawaiian'] == 1:
#         return 'Haw/Pac Isl.'
#     if row['eri_white'] == 1:
#         return 'White'
#     return 'Other'

# df.apply(label_race, axis=1)

##### tmp - debugging: END

In [272]:
MOVIES_FILENAME = "movies.dat"
MOVLENS_DIR = "../src/data/local_data/raw/datasets/ml-1m"
MOVIES_PATH = f"{MOVLENS_DIR}/{MOVIES_FILENAME}"
print(MOVIES_PATH)

../src/data/local_data/raw/datasets/ml-1m/movies.dat

In [684]:
MOVIES_DATA_COLUMNS = ["target_movie_id", "target_movie_title", "genres_raw"] # genres_raw

movies_df = pd.read_csv(
    os.path.join(MOVLENS_DIR, MOVIES_FILENAME),
    sep="::",
    names=MOVIES_DATA_COLUMNS,
    encoding="unicode_escape"
)

movies_df.head(3)

   target_movie_id       target_movie_title                    genres_raw
0                1         Toy Story (1995)   Animation|Children's|Comedy
1                2           Jumanji (1995)  Adventure|Children's|Fantasy
2                3  Grumpier Old Men (1995)                Comedy|Romance

In [685]:
import re

UNKNOWN_STR = "UNK"

# movie year
movies_df['target_movie_year'] = movies_df['target_movie_title'].apply(
    lambda movie_name: re.search('\((\d*)\)', movie_name).groups(1)[0]
)
movies_df["target_movie_year"] = movies_df["target_movie_year"].apply(int)

# movie_id
movies_df["target_movie_id"] = movies_df["target_movie_id"].apply(str)
movies_df['target_movie_id'] = movies_df.apply(
    # lambda row: tf.compat.as_bytes(row.target_movie_id),
    lambda row: row.target_movie_id,
    axis = 1
)

# movie titles
movies_df['target_movie_title'] = movies_df.apply(
    # lambda row: tf.compat.as_bytes(row.target_movie_title),
    lambda row: row.target_movie_title,
    axis = 1
)

# genres
movies_df['target_movie_genres'] = movies_df.apply(
    # lambda row: str(row.genres_raw).split("|"),
    # lambda row: [tf.compat.as_bytes(z) for z in str(row.genres_raw).split("|")],
    lambda row: [z for z in str(row.genres_raw).split("|")],
    axis = 1
)
movies_df['genre_pad_values'] = movies_df.apply(
    # lambda row: [tf.compat.as_bytes(UNKNOWN_STR) for _ in range(env_config.MAX_GENRE_LENGTH - len(row.target_movie_genres))],
    lambda row: [UNKNOWN_STR for _ in range(env_config.MAX_GENRE_LENGTH - len(row.target_movie_genres))],
    axis = 1
)

# update the genre col
movies_df.apply(
    lambda row: row.target_movie_genres.extend(row.genre_pad_values),
    axis = 1
)

# drop cols
movies_df = movies_df.drop(
    columns=[
        'genre_pad_values', 
        # 'genres_n', 
        'genres_raw'
    ]
)

# uniques
movies_df = movies_df.drop_duplicates(
    subset=["target_movie_id"],
) 

# inspect df
print(movies_df.shape)
movies_df.head(3)

(3883, 4)

,target_movie_id,target_movie_title,target_movie_year,target_movie_genres
0,1,Toy Story (1995),1995,"[Animation, Children's, Comedy, UNK, UNK, UNK,..."
1,2,Jumanji (1995),1995,"[Adventure, Children's, Fantasy, UNK, UNK, UNK..."
2,3,Grumpier Old Men (1995),1995,"[Comedy, Romance, UNK, UNK, UNK, UNK, UNK, UNK..."

In [727]:
# dict_df = dict(movies_df)
# # dict_df['target_movie_id']
# # dict_df['target_movie_title']
# # dict_df['target_movie_year']
# dict_df['target_movie_genres'][0]

# records = movies_df.to_dict('records')
# records[0]

# drop cols
movies_df = movies_df.drop(
    columns=[
        # 'jts_movie_genre',
        # "movie_genre_string",
        # 'genres_n', 
        # 'genres_raw'
    ]
)
movies_df.head()

,target_movie_id,target_movie_title,target_movie_year,target_movie_genres
0,1,Toy Story (1995),1995,"[Animation, Children's, Comedy, UNK, UNK, UNK,..."
1,2,Jumanji (1995),1995,"[Adventure, Children's, Fantasy, UNK, UNK, UNK..."
2,3,Grumpier Old Men (1995),1995,"[Comedy, Romance, UNK, UNK, UNK, UNK, UNK, UNK..."
3,4,Waiting to Exhale (1995),1995,"[Comedy, Drama, UNK, UNK, UNK, UNK, UNK, UNK, ..."
4,5,Father of the Bride Part II (1995),1995,"[Comedy, UNK, UNK, UNK, UNK, UNK, UNK, UNK, UN..."

In [728]:
# movies_df['movie_genre_string'] = movies_df['target_movie_genres'].map(str)
# movies_df['jts_movie_genre'] = movies_df['target_movie_genres'][0]

movies_df['target_movie_genre'] = movies_df['target_movie_genres'].apply(lambda x: x[0])
movies_df.head(3)

,target_movie_id,target_movie_title,target_movie_year,target_movie_genres,target_movie_genre
0,1,Toy Story (1995),1995,"[Animation, Children's, Comedy, UNK, UNK, UNK,...",Animation
1,2,Jumanji (1995),1995,"[Adventure, Children's, Fantasy, UNK, UNK, UNK...",Adventure
2,3,Grumpier Old Men (1995),1995,"[Comedy, Romance, UNK, UNK, UNK, UNK, UNK, UNK...",Comedy

In [729]:
preped_movies_df = movies_df.drop(
    columns=['target_movie_genres']
)

preped_movies_df.head(3)

,target_movie_id,target_movie_title,target_movie_year,target_movie_genre
0,1,Toy Story (1995),1995,Animation
1,2,Jumanji (1995),1995,Adventure
2,3,Grumpier Old Men (1995),1995,Comedy

#### load BQ table from dataframe

In [730]:
BQ_DATASET_NAME = f"{env_config.BUCKET_NAME.lower().replace(env_config.PROJECT_ID,'')}"
BQ_DATASET_NAME = BQ_DATASET_NAME.replace('bucket','').replace('-','_').replace('__','_').rstrip("_")

BQ_TABLE_NAME = "candidates_v2"

BQ_TABLE_REF = f"{env_config.PROJECT_ID}.{BQ_DATASET_NAME}.{BQ_TABLE_NAME}"

print(f"BUCKET_NAME     = {env_config.BUCKET_NAME}")
print(f"BUCKET_URI      = {env_config.BUCKET_URI}")
print(f"BQ_DATASET_NAME = {BQ_DATASET_NAME}")
print(f"BQ_TABLE_REF    = {BQ_TABLE_REF}")

BUCKET_NAME     = jt-towers-v1-hybrid-vertex-bucket
BUCKET_URI      = gs://jt-towers-v1-hybrid-vertex-bucket
BQ_DATASET_NAME = jt_towers_v1
BQ_TABLE_REF    = hybrid-vertex.jt_towers_v1.candidates_v2

In [731]:
job_config = bigquery.LoadJobConfig(
    schema=[        
        ## target item
        # bigquery.SchemaField("target_movie_rating", bigquery.enums.SqlTypeNames.FLOAT),
        # bigquery.SchemaField("target_rating_timestamp", bigquery.enums.SqlTypeNames.INTEGER),
        bigquery.SchemaField("target_movie_id", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("target_movie_title", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("target_movie_year", bigquery.enums.SqlTypeNames.INTEGER),
        bigquery.SchemaField("target_movie_genre", bigquery.enums.SqlTypeNames.STRING), # mode="REPEATED"
        # bigquery.SchemaField("movie_genre_string", bigquery.enums.SqlTypeNames.STRING),
    ],
    # source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
)

In [732]:
# using dataframe
load_job = bqclient.load_table_from_dataframe(
    preped_movies_df, BQ_TABLE_REF, job_config=job_config
)
    
load_job.result()  # Wait for the job to complete.

table = bqclient.get_table(BQ_TABLE_REF)  # Make an API request.
print(
    "Loaded {} rows and {} columns to {}".format(
        table.num_rows, len(table.schema), BQ_TABLE_REF
    )
)

Loaded 3883 rows and 4 columns to hybrid-vertex.jt_towers_v1.candidates_v2

In [733]:
query = f"""
SELECT 
  target_movie_id,
  target_movie_title,
  target_movie_year,
  target_movie_genre,
FROM `{BQ_TABLE_REF}` 
WHERE CAST(target_movie_id AS INT64) < 10 
ORDER BY CAST(target_movie_id AS INT64) ASC LIMIT 5;
"""
# print(query)

bqclient.query(query).to_dataframe()

,target_movie_id,target_movie_title,target_movie_year,target_movie_genre
0,1,Toy Story (1995),1995,Animation
1,2,Jumanji (1995),1995,Adventure
2,3,Grumpier Old Men (1995),1995,Comedy
3,4,Waiting to Exhale (1995),1995,Comedy
4,5,Father of the Bride Part II (1995),1995,Comedy

# BigQuery to TFRecord template

see guide [here](https://cloud.google.com/dataflow/docs/guides/templates/provided/bigquery-to-tfrecords#gcloud)

**required parameters**

* **readQuery** : A BigQuery SQL query that extracts data from the source. For example, select * from dataset1.sample_table.
* **outputDirectory** : The top-level Cloud Storage path prefix to use when writing the training, testing, and validation TFRecord files. Subdirectories for resulting training, testing, and validation TFRecord files are automatically generated from outputDirectory. For example, gs://mybucket/output/train (Example: gs://mybucket/output).

In [738]:
JOB_NAME="create-candidate-tfrs"
REGION_NAME="us-central1"
READ_QUERY="SELECT * from `hybrid-vertex.jt_towers_v1.candidates_v2`"
OUTPUT_DIRECTORY= f"{BUCKET_URI}/candidates"
TRAINING_PERCENTAGE=1
TESTING_PERCENTAGE=0
VALIDATION_PERCENTAGE=0
OUTPUT_FILENAME_SUFFIX="tfrs"
TEMPLATE_VERSION="latest"

In [739]:
COMMAND=f"""
gcloud dataflow jobs run {JOB_NAME} \
    --gcs-location gs://dataflow-templates-{REGION_NAME}/{TEMPLATE_VERSION}/Cloud_BigQuery_to_GCS_TensorFlow_Records \
    --region {REGION_NAME} \
    --parameters \
readQuery={READ_QUERY},\
outputDirectory={OUTPUT_DIRECTORY},\
trainingPercentage={TRAINING_PERCENTAGE},\
testingPercentage={TESTING_PERCENTAGE},\
validationPercentage={VALIDATION_PERCENTAGE},\
outputSuffix={OUTPUT_FILENAME_SUFFIX}
"""
print(COMMAND)

gcloud dataflow jobs run create-candidate-tfrs     --gcs-location gs://dataflow-templates-us-central1/latest/Cloud_BigQuery_to_GCS_TensorFlow_Records     --region us-central1     --parameters readQuery=SELECT * from `hybrid-vertex.jt_towers_v1.candidates_v2`,outputDirectory=gs://jt-towers-v1-hybrid-vertex-bucket/candidates,trainingPercentage=1,testingPercentage=0,validationPercentage=0,outputSuffix=tfrs

In [ ]:
# gcloud dataflow jobs run create-candidate-tfrs 
# --gcs-location gs://dataflow-templates-us-central1/latest/Cloud_BigQuery_to_GCS_TensorFlow_Records 
# --region us-central1 
# --parameters readQuery="SELECT * from hybrid-vertex.jt_towers_v1.candidates_v2",outputDirectory="gs://jt-towers-v1-hybrid-vertex-bucket/candidates",trainingPercentage=1,testingPercentage=0,validationPercentage=0,outputSuffix=tfrs

In [741]:
!gsutil ls $OUTPUT_DIRECTORY
! gsutil cp gs://jt-towers-v1-hybrid-vertex-bucket/candidates/train/output-00000-of-00001.tfrecord

gs://jt-towers-v1-hybrid-vertex-bucket/candidates/train/

## Check candidates TF Record file

In [743]:
candidate_features = {
    'target_movie_id': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
    'target_movie_genre': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
    'target_movie_year': tf.io.FixedLenFeature(shape=(), dtype=tf.int64),
    'target_movie_title': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
}
def _parse_candidates_fn(example_proto):
    return tf.io.parse_single_example(
        example_proto, candidate_features
    )

CANDIDATE_FILES = [
    "gs://jt-towers-v1-hybrid-vertex-bucket/candidates/train/output-00000-of-00001.tfrecord"
]

In [745]:
candidate_dataset = tf.data.TFRecordDataset(CANDIDATE_FILES)

parsed_candidate_dataset = candidate_dataset.map(_parse_candidates_fn)

for x in parsed_candidate_dataset.batch(1).take(1):
    pprint(x)

{'target_movie_genre': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Action'], dtype=object)>,
 'target_movie_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'1480'], dtype=object)>,
 'target_movie_title': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b"Smilla's Sense of Snow (1997)"], dtype=object)>,
 'target_movie_year': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1997])>}

# gitignore

In [ ]:
rm -rf `find . -name "*.ipynb_checkpoints" -o -name "*.cpython-310.pyc" -o -name "__pycache__"`

In [26]:
%%writefile .gitignore
*.cpython-310.pyc
*checkpoint*
*.ipynb_checkpoints/*
*/data/local_data/*
*.csv
*__pycache__
*cpython-37.pyc
.gitignore

Writing .gitignore

# Clean up

In [ ]:
# (optional) delete local
# cd src/data
# rm -rf local_data

**finished**