# Movielens download

1. download MovieLens 1M public dataset
2. Write datasets to TF-Records
3. Generate dataset vocabulary and look-up dictionaries

## imports

In [1]:
import sys
sys.path.append("..")
import env_config

In [2]:
print(f"PREFIX: {env_config.PREFIX}")
print(f"PROJECT_ID: {env_config.PROJECT_ID}")
print(f"LOCATION: {env_config.LOCATION}")

PREFIX: jt-towers-v1
PROJECT_ID: hybrid-vertex
LOCATION: us-central1

In [ ]:
!pwd

In [29]:
import os
import json
from pprint import pprint
import pickle as pkl
import numpy as np
import pandas as pd

import logging
logging.disable(logging.WARNING)
import warnings
warnings.filterwarnings('ignore')

# tensorflow
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
# import tensorflow_datasets as tfds

# google cloud
from google.cloud import aiplatform, storage, bigquery

# cloud storage client
storage_client = storage.Client(project=env_config.PROJECT_ID)
bqclient = bigquery.Client(project=env_config.PROJECT_ID)

# Vertex client
aiplatform.init(project=env_config.PROJECT_ID, location=env_config.LOCATION)

sys.path.append("..")
from src.data import data_utils as data_utils

## config: data download and prep

In [5]:
LOCAL_OUTPUT_DIR     = "local_data/examples"
LOCAL_EXTRACT_DIR    = "local_data/raw"

MIN_TIMELINE_LENGTH  = 3
MIN_RATING           = 1

NUM_TRAIN_RECORDS    = 8
NUM_VAL_RECORDS      = 3

BUILD_VOCAB          = True

print(f"EXAMPLE_GEN_GCS_PATH : {env_config.EXAMPLE_GEN_GCS_PATH}")
print(f"TF_RECORD_PREFIX     : {env_config.TF_RECORD_PREFIX}")
print(f"MAX_CONTEXT_LENGTH   : {env_config.MAX_CONTEXT_LENGTH}")
print(f"MAX_GENRE_LENGTH     : {env_config.MAX_GENRE_LENGTH}")

EXAMPLE_GEN_GCS_PATH : data/movielens/m1m_v2
TF_RECORD_PREFIX     : ml1m
MAX_CONTEXT_LENGTH   : 10
MAX_GENRE_LENGTH     : 10

#### create GCS bucket

In [6]:
REGION=env_config.LOCATION
BUCKET_URI=f"gs://{env_config.BUCKET_NAME}"

In [8]:
!gsutil mb -l $REGION $BUCKET_URI

### copy these commands to command line terminal

In [7]:
print("copy these commands into terminal:\n")
print(f"export PROJECT_ID={env_config.PROJECT_ID}")
print(f"export BUCKET_NAME={env_config.BUCKET_NAME}")
print(f"export EXAMPLE_GEN_GCS_PATH={env_config.EXAMPLE_GEN_GCS_PATH}")
print(f"export TF_RECORD_PREFIX={env_config.TF_RECORD_PREFIX}")
print(f"export MAX_GENRE_LENGTH={env_config.MAX_GENRE_LENGTH}")
print(f"export MAX_CONTEXT_LENGTH={env_config.MAX_CONTEXT_LENGTH}")
print(f"export LOCAL_EXTRACT_DIR={LOCAL_EXTRACT_DIR}")
print(f"export LOCAL_OUTPUT_DIR={LOCAL_OUTPUT_DIR}")
print(f"export MIN_TIMELINE_LENGTH={MIN_TIMELINE_LENGTH}")
print(f"export MIN_RATING={MIN_RATING}")
print(f"export BUILD_VOCAB={BUILD_VOCAB}")
print(f"export NUM_TRAIN_RECORDS={NUM_TRAIN_RECORDS}")
print(f"export NUM_VAL_RECORDS={NUM_VAL_RECORDS}")
print(f"chmod +x example_gen_movielens.py")

copy these commands into terminal:

export PROJECT_ID=hybrid-vertex
export BUCKET_NAME=jt-towers-v1-hybrid-vertex-bucket
export EXAMPLE_GEN_GCS_PATH=data/movielens/m1m_v2
export TF_RECORD_PREFIX=ml1m
export MAX_GENRE_LENGTH=10
export MAX_CONTEXT_LENGTH=10
export LOCAL_EXTRACT_DIR=local_data/raw
export LOCAL_OUTPUT_DIR=local_data/examples
export MIN_TIMELINE_LENGTH=3
export MIN_RATING=1
export BUILD_VOCAB=True
export NUM_TRAIN_RECORDS=8
export NUM_VAL_RECORDS=3
chmod +x example_gen_movielens.py

In [8]:
data_gen_command = """python example_gen_movielens.py --project_id=$PROJECT_ID --gcs_bucket_name=$BUCKET_NAME \
--gcs_data_path_prefix=$EXAMPLE_GEN_GCS_PATH \
--tfrecord_prefix=$TF_RECORD_PREFIX \
--local_data_dir=$LOCAL_EXTRACT_DIR \
--local_output_dir=$LOCAL_OUTPUT_DIR \
--min_timeline_length=$MIN_TIMELINE_LENGTH \
--max_context_length=$MAX_CONTEXT_LENGTH \
--max_context_movie_genre_length=$MAX_GENRE_LENGTH \
--min_rating=$MIN_RATING \
--train_data_fraction=0.9 \
--build_vocabs=$BUILD_VOCAB \
--num_train_tfrecords=$NUM_TRAIN_RECORDS \
--num_test_tfrecords=$NUM_VAL_RECORDS \
"""
print(data_gen_command)

python example_gen_movielens.py --project_id=$PROJECT_ID --gcs_bucket_name=$BUCKET_NAME --gcs_data_path_prefix=$EXAMPLE_GEN_GCS_PATH --tfrecord_prefix=$TF_RECORD_PREFIX --local_data_dir=$LOCAL_EXTRACT_DIR --local_output_dir=$LOCAL_OUTPUT_DIR --min_timeline_length=$MIN_TIMELINE_LENGTH --max_context_length=$MAX_CONTEXT_LENGTH --max_context_movie_genre_length=$MAX_GENRE_LENGTH --min_rating=$MIN_RATING --train_data_fraction=0.9 --build_vocabs=$BUILD_VOCAB --num_train_tfrecords=$NUM_TRAIN_RECORDS --num_test_tfrecords=$NUM_VAL_RECORDS

**Train**

```
tf_examples_len  : 894752
num_of_records   : 8
files_per_record : 111844
```

**val**

```
tf_examples_len  : 99417
num_of_records   : 3
files_per_record : 33139
```

# Confim tfrecords

In [9]:
GCS_DATA_PATH = f"{env_config.BUCKET_URI}/{env_config.EXAMPLE_GEN_GCS_PATH}"
print(f"GCS_DATA_PATH : {GCS_DATA_PATH}")

! gsutil ls $GCS_DATA_PATH

GCS_DATA_PATH : gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2
gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/
gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/val/
gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/vocabs/

In [10]:
all_files = []
for blob in storage_client.list_blobs(
    f"{env_config.BUCKET_NAME}", 
    prefix=f'{env_config.EXAMPLE_GEN_GCS_PATH}/train/', 
    # delimiter='/'
):
    if '.tfrecord' in blob.name:
        all_files.append(blob.public_url.replace("https://storage.googleapis.com/", "gs://"))
        
all_files

['gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-001-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-002-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-003-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-004-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-005-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-006-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-007-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-008-of-008.tfrecord']

In [11]:
for blob in storage_client.list_blobs(
    f"{env_config.BUCKET_NAME}", 
    prefix=f'{env_config.EXAMPLE_GEN_GCS_PATH}/val/', 
    # delimiter='/'
):
    if '.tfrecord' in blob.name:
        all_files.append(blob.public_url.replace("https://storage.googleapis.com/", "gs://"))
        
all_files

['gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-001-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-002-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-003-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-004-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-005-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-006-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-007-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/train/ml1m-008-of-008.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/val/ml1m-001-of-003.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/val/ml1m-002-of-003.tfrecord',
 'gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/val/ml1m-003-of-003.tfrecord']

In [12]:
mv_dataset = tf.data.TFRecordDataset(all_files)
mv_dataset = mv_dataset.map(data_utils._parse_function)

for x in mv_dataset.batch(1).take(1):
    pprint(x)

{'context_movie_genre': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'Adventure', b'Drama', b'Romance', b'Adventure', b"Children's",
        b'Comedy', b'Adventure', b"Children's", b'Comedy', b'Action']],
      dtype=object)>,
 'context_movie_id': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'3764', b'1982', b'1981', b'3636', b'2011', b'2846', b'2055',
        b'1109', b'2820', b'583']], dtype=object)>,
 'context_movie_rating': <tf.Tensor: shape=(1, 10), dtype=float32, numpy=array([[3., 3., 2., 2., 4., 4., 3., 4., 5., 4.]], dtype=float32)>,
 'context_movie_title': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'Bronco Billy (1980)', b'Herbie Goes to Monte Carlo (1977)',
        b'Herbie Goes Bananas (1980)', b'Bird on a Wire (1990)',
        b'Lady and the Tramp (1955)', b'Risky Business (1983)',
        b'Addams Family, The (1991)',
        b'Return of the Pink Panther, The (1974)',
        b'Mystery, Alaska (1999)', b'Ghost (1990)']], dtype=object)>,
 'context_movie_year': <tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[1980, 1977, 1980, 1990, 1955, 1983, 1991, 1974, 1999, 1990]])>,
 'context_rating_timestamp': <tf.Tensor: shape=(1, 10), dtype=int64, numpy=
array([[971978345, 971978377, 971978397, 971978397, 971978464, 971978777,
        971978844, 971978883, 971978883, 971978924]])>,
 'target_movie_genre': <tf.Tensor: shape=(1, 10), dtype=string, numpy=
array([[b'Comedy', b'Romance', b'UNK', b'UNK', b'UNK', b'UNK', b'UNK',
        b'UNK', b'UNK', b'UNK']], dtype=object)>,
 'target_movie_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'841'], dtype=object)>,
 'target_movie_rating': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([2.], dtype=float32)>,
 'target_movie_title': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'Tin Cup (1996)'], dtype=object)>,
 'target_movie_year': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1996])>,
 'target_rating_timestamp': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([971978941])>,
 'user_age': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([25])>,
 'user_gender': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'M'], dtype=object)>,
 'user_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'2908'], dtype=object)>,
 'user_occupation_text': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'executive/managerial'], dtype=object)>,
 'user_zip_code': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'43228'], dtype=object)>}

# Validate vocab file

In [13]:
VOCAB_FILENAME="vocab_dict.pkl"

In [14]:
EXISTING_VOCAB_FILE = f'gs://{env_config.BUCKET_NAME}/{env_config.EXAMPLE_GEN_GCS_PATH}/vocabs/{VOCAB_FILENAME}'
print(f"Downloading vocab...")

os.system(f'gsutil -q cp {EXISTING_VOCAB_FILE} .')
print(f"Downloaded vocab from: {EXISTING_VOCAB_FILE}\n")

filehandler = open(VOCAB_FILENAME, 'rb')
vocab_dict = pkl.load(filehandler)
filehandler.close()

for key in vocab_dict.keys():
    pprint(key)

Downloading vocab...
Downloaded vocab from: gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/vocabs/vocab_dict.pkl

'movie_id'
'movie_year'
'movie_genre'
'movie_title'
'user_id'
'user_gender_vocab'
'user_age_vocab'
'user_occ_vocab'
'user_zip_vocab'
'min_timestamp'
'max_timestamp'
'timestamp_buckets'

In [15]:
list_of_years = vocab_dict['movie_year'] #.tolist()

min_yr = min(list_of_years)
max_yr = max(list_of_years)

print(f"min: {min_yr}; max: {max_yr}")

min: 0; max: 2000

In [16]:
MOVIELENS_NUM_MOVIES = len(vocab_dict['movie_id'])
MOVIELENS_NUM_USERS = len(vocab_dict['user_id'])

print(f"MOVIELENS_NUM_MOVIES : {MOVIELENS_NUM_MOVIES}")
print(f"MOVIELENS_NUM_USERS  : {MOVIELENS_NUM_USERS}")

MOVIELENS_NUM_MOVIES : 3884
MOVIELENS_NUM_USERS  : 6041

# Create look-up dictionaries

In [17]:
USER_AGE_LOOKUP = data_utils.get_dictionary_lookup_by_tf_data_key(
    key = 'user_age'
    , dataset = mv_dataset
)

USER_AGE_DIM = len(USER_AGE_LOOKUP)
print(f"USER_AGE_DIM: {USER_AGE_DIM}")


USER_OCC_LOOKUP = data_utils.get_dictionary_lookup_by_tf_data_key(
    key = 'user_occupation_text'
    , dataset= mv_dataset
)
USER_OCC_LOOKUP[b''] = 21
USER_OCC_DIM = len(USER_OCC_LOOKUP)
print(f"USER_OCC_DIM: {USER_OCC_DIM}")

USER_AGE_DIM: 8
USER_OCC_DIM: 22

In [18]:
config = f'''
USER_AGE_LOOKUP       = {USER_AGE_LOOKUP}
USER_AGE_DIM          = {USER_AGE_DIM}
USER_OCC_LOOKUP       = {USER_OCC_LOOKUP}
USER_OCC_DIM          = {USER_OCC_DIM}
MOVIELENS_NUM_MOVIES  = {MOVIELENS_NUM_MOVIES}
MOVIELENS_NUM_USERS   = {MOVIELENS_NUM_USERS}
'''
    
with open(f'../src/data/mv_lookup_dicts.py', 'w') as f:
    f.write(config)

In [15]:
ds_data = [x for x in mv_dataset.take(10).as_numpy_iterator()]
df = pd.DataFrame(ds_data)
df.head()

,context_movie_genre,context_movie_id,context_movie_rating,context_movie_title,context_movie_year,context_rating_timestamp,target_movie_genre,target_movie_id,target_movie_rating,target_movie_title,target_movie_year,target_rating_timestamp,user_age,user_gender,user_id,user_occupation_text,user_zip_code
0,"[b'Adventure', b'Drama', b'Romance', b'Adventu...","[b'3764', b'1982', b'1981', b'3636', b'2011', ...","[3.0, 3.0, 2.0, 2.0, 4.0, 4.0, 3.0, 4.0, 5.0, ...","[b'Bronco Billy (1980)', b'Herbie Goes to Mont...","[1980, 1977, 1980, 1990, 1955, 1983, 1991, 197...","[971978345, 971978377, 971978397, 971978397, 9...","[b'Comedy', b'Romance', b'UNK', b'UNK', b'UNK'...",b'841',2.0,b'Tin Cup (1996)',1996,971978941,25,b'M',b'2908',b'executive/managerial',b'43228'
1,"[b'Action', b'Thriller', b'Action', b'Drama', ...","[b'3486', b'3509', b'3682', b'3684', b'3686', ...","[3.0, 4.0, 5.0, 2.0, 4.0, 5.0, 3.0, 5.0, 5.0, ...","[b'U-571 (2000)', b'Gladiator (2000)', b'Chick...","[2000, 2000, 2000, 2000, 2000, 1996, 1999, 200...","[975201009, 975201009, 975201009, 975201009, 9...","[b'Action', b'Adventure', b'Sci-Fi', b'UNK', b...",b'3794',3.0,b'Godzilla 2000 (Gojira ni-sen mireniamu) (1999)',1999,975201201,56,b'M',b'921',b'self-employed',b'48009'
2,"[b'Drama', b'Animation', b""Children's"", b'Musi...","[b'768', b'360', b'1591', b'2608', b'3037', b'...","[4.0, 3.0, 3.0, 4.0, 5.0, 2.0, 2.0, 4.0, 3.0, ...","[b'Trainspotting (1996)', b'Lion King, The (19...","[1996, 1994, 1997, 1999, 1990, 1996, 1997, 199...","[963844107, 963844122, 963844158, 963844158, 9...","[b'Adventure', b'Drama', b'Western', b'UNK', b...",b'586',4.0,b'Dances with Wolves (1990)',1990,963844233,35,b'M',b'4665',b'academic/educator',b'53704'
3,"[b'Comedy', b'Romance', b'Action', b'Thriller'...","[b'841', b'1349', b'1077', b'583', b'3194', b'...","[5.0, 2.0, 4.0, 3.0, 4.0, 2.0, 5.0, 3.0, 4.0, ...","[b'Tin Cup (1996)', b'Die Hard 2 (1990)', b'Do...","[1996, 1990, 1991, 1990, 1992, 1990, 1996, 199...","[958172272, 958172290, 958172290, 958172319, 9...","[b'Comedy', b'Fantasy', b'Romance', b'Sci-Fi',...",b'778',3.0,"b'Nutty Professor, The (1996)'",1996,958172648,25,b'M',b'5770',b'executive/managerial',b'95616'
4,"[b'Action', b'Adventure', b'Sci-Fi', b'Thrille...","[b'838', b'865', b'108', b'1101', b'884', b'30...","[1.0, 1.0, 3.0, 5.0, 5.0, 5.0, 2.0, 1.0, 4.0, ...","[b'Escape from L.A. (1996)', b'Police Story 4:...","[1996, 1993, 1995, 1996, 1994, 1948, 1999, 195...","[958835045, 958835133, 958835133, 958835554, 9...","[b'Drama', b'War', b'UNK', b'UNK', b'UNK', b'U...",b'1190',2.0,b'Apocalypse Now (1979)',1979,958835705,25,b'M',b'5655',b'scientist',b'03755'

# Create parsed candidate dataset

> for help, see [Load data from DataFrame](https://cloud.google.com/bigquery/docs/samples/bigquery-load-table-dataframe#code-sample) from BigQuery code samples

##### tmp - debugging: END

In [23]:
MOVIES_FILENAME = "movies.dat"
MOVLENS_DIR = "../src/data/local_data/raw/datasets/ml-1m"
MOVIES_PATH = f"{MOVLENS_DIR}/{MOVIES_FILENAME}"
print(MOVIES_PATH)

../src/data/local_data/raw/datasets/ml-1m/movies.dat

In [24]:
MOVIES_DATA_COLUMNS = ["target_movie_id", "target_movie_title", "genres_raw"] # genres_raw

movies_df = pd.read_csv(
    os.path.join(MOVLENS_DIR, MOVIES_FILENAME),
    sep="::",
    names=MOVIES_DATA_COLUMNS,
    encoding="unicode_escape"
)

movies_df.head(3)

   target_movie_id       target_movie_title                    genres_raw
0                1         Toy Story (1995)   Animation|Children's|Comedy
1                2           Jumanji (1995)  Adventure|Children's|Fantasy
2                3  Grumpier Old Men (1995)                Comedy|Romance

In [25]:
import re

UNKNOWN_STR = "UNK"

# movie year
movies_df['target_movie_year'] = movies_df['target_movie_title'].apply(
    lambda movie_name: re.search('\((\d*)\)', movie_name).groups(1)[0]
)
movies_df["target_movie_year"] = movies_df["target_movie_year"].apply(int)

# movie_id
movies_df["target_movie_id"] = movies_df["target_movie_id"].apply(str)
movies_df['target_movie_id'] = movies_df.apply(
    # lambda row: tf.compat.as_bytes(row.target_movie_id),
    lambda row: row.target_movie_id,
    axis = 1
)

# movie titles
movies_df['target_movie_title'] = movies_df.apply(
    # lambda row: tf.compat.as_bytes(row.target_movie_title),
    lambda row: row.target_movie_title,
    axis = 1
)

# genres
movies_df['target_movie_genres'] = movies_df.apply(
    # lambda row: str(row.genres_raw).split("|"),
    # lambda row: [tf.compat.as_bytes(z) for z in str(row.genres_raw).split("|")],
    lambda row: [z for z in str(row.genres_raw).split("|")],
    axis = 1
)
movies_df['genre_pad_values'] = movies_df.apply(
    # lambda row: [tf.compat.as_bytes(UNKNOWN_STR) for _ in range(env_config.MAX_GENRE_LENGTH - len(row.target_movie_genres))],
    lambda row: [UNKNOWN_STR for _ in range(env_config.MAX_GENRE_LENGTH - len(row.target_movie_genres))],
    axis = 1
)

# update the genre col
movies_df.apply(
    lambda row: row.target_movie_genres.extend(row.genre_pad_values),
    axis = 1
)

# drop cols
movies_df = movies_df.drop(
    columns=[
        'genre_pad_values', 
        # 'genres_n', 
        'genres_raw'
    ]
)

# uniques
movies_df = movies_df.drop_duplicates(
    subset=["target_movie_id"],
) 

# inspect df
print(movies_df.shape)
movies_df.head(3)

(3883, 4)

,target_movie_id,target_movie_title,target_movie_year,target_movie_genres
0,1,Toy Story (1995),1995,"[Animation, Children's, Comedy, UNK, UNK, UNK,..."
1,2,Jumanji (1995),1995,"[Adventure, Children's, Fantasy, UNK, UNK, UNK..."
2,3,Grumpier Old Men (1995),1995,"[Comedy, Romance, UNK, UNK, UNK, UNK, UNK, UNK..."

In [26]:
# movies_df['movie_genre_string'] = movies_df['target_movie_genres'].map(str)
# movies_df['jts_movie_genre'] = movies_df['target_movie_genres'][0]

movies_df['target_movie_genre'] = movies_df['target_movie_genres'].apply(lambda x: x[0])
movies_df.head(3)

,target_movie_id,target_movie_title,target_movie_year,target_movie_genres,target_movie_genre
0,1,Toy Story (1995),1995,"[Animation, Children's, Comedy, UNK, UNK, UNK,...",Animation
1,2,Jumanji (1995),1995,"[Adventure, Children's, Fantasy, UNK, UNK, UNK...",Adventure
2,3,Grumpier Old Men (1995),1995,"[Comedy, Romance, UNK, UNK, UNK, UNK, UNK, UNK...",Comedy

In [27]:
preped_movies_df = movies_df.drop(
    columns=[
        "target_movie_genres", 
        "target_movie_genre"
    ]
)

preped_movies_df.head(3)

  target_movie_id       target_movie_title  target_movie_year
0               1         Toy Story (1995)               1995
1               2           Jumanji (1995)               1995
2               3  Grumpier Old Men (1995)               1995

#### load BQ table from dataframe

In [28]:
BQ_DATASET_NAME = f"{env_config.BUCKET_NAME.lower().replace(env_config.PROJECT_ID,'')}"
BQ_DATASET_NAME = BQ_DATASET_NAME.replace('bucket','').replace('-','_').replace('__','_').rstrip("_")

BQ_TABLE_NAME = "candidates_v3"

BQ_TABLE_REF = f"{env_config.PROJECT_ID}.{BQ_DATASET_NAME}.{BQ_TABLE_NAME}"

print(f"BUCKET_NAME     = {env_config.BUCKET_NAME}")
print(f"BUCKET_URI      = {env_config.BUCKET_URI}")
print(f"BQ_DATASET_NAME = {BQ_DATASET_NAME}")
print(f"BQ_TABLE_REF    = {BQ_TABLE_REF}")

BUCKET_NAME     = jt-towers-v1-hybrid-vertex-bucket
BUCKET_URI      = gs://jt-towers-v1-hybrid-vertex-bucket
BQ_DATASET_NAME = jt_towers_v1
BQ_TABLE_REF    = hybrid-vertex.jt_towers_v1.candidates_v3

In [30]:
job_config = bigquery.LoadJobConfig(
    schema=[        
        ## target item
        # bigquery.SchemaField("target_movie_rating", bigquery.enums.SqlTypeNames.FLOAT),
        # bigquery.SchemaField("target_rating_timestamp", bigquery.enums.SqlTypeNames.INTEGER),
        bigquery.SchemaField("target_movie_id", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("target_movie_title", bigquery.enums.SqlTypeNames.STRING),
        bigquery.SchemaField("target_movie_year", bigquery.enums.SqlTypeNames.INTEGER),
        # bigquery.SchemaField("target_movie_genre", bigquery.enums.SqlTypeNames.STRING), # mode="REPEATED"
    ],
    # source_format=bigquery.SourceFormat.NEWLINE_DELIMITED_JSON,
)

In [31]:
# using dataframe
load_job = bqclient.load_table_from_dataframe(
    preped_movies_df, BQ_TABLE_REF, job_config=job_config
)
    
load_job.result()  # Wait for the job to complete.

table = bqclient.get_table(BQ_TABLE_REF)  # Make an API request.
print(
    "Loaded {} rows and {} columns to {}".format(
        table.num_rows, len(table.schema), BQ_TABLE_REF
    )
)

Loaded 3883 rows and 3 columns to hybrid-vertex.jt_towers_v1.candidates_v3

In [33]:
  # target_movie_genre,
    
query = f"""
SELECT 
  target_movie_id,
  target_movie_title,
  target_movie_year
FROM `{BQ_TABLE_REF}` 
WHERE CAST(target_movie_id AS INT64) < 10 
ORDER BY CAST(target_movie_id AS INT64) ASC LIMIT 5;
"""
# print(query)

# bqclient.query(query).to_dataframe()

# BigQuery to TFRecord template

see guide [here](https://cloud.google.com/dataflow/docs/guides/templates/provided/bigquery-to-tfrecords#gcloud)

**required parameters**

* **readQuery** : A BigQuery SQL query that extracts data from the source. For example, select * from dataset1.sample_table.
* **outputDirectory** : The top-level Cloud Storage path prefix to use when writing the training, testing, and validation TFRecord files. Subdirectories for resulting training, testing, and validation TFRecord files are automatically generated from outputDirectory. For example, gs://mybucket/output/train (Example: gs://mybucket/output).

In [44]:
JOB_NAME="create-candidate-tfrs"
REGION_NAME="us-central1"
READ_QUERY=f"SELECT * from `{env_config.PROJECT_ID}.{BQ_DATASET_NAME}.{BQ_TABLE_NAME}`"
OUTPUT_DIRECTORY= f"{BUCKET_URI}/{env_config.EXAMPLE_GEN_GCS_PATH}/candidates"
TRAINING_PERCENTAGE=1
TESTING_PERCENTAGE=0
VALIDATION_PERCENTAGE=0
OUTPUT_FILENAME_SUFFIX=".tfrecord"
TEMPLATE_VERSION="latest"

print(READ_QUERY)

SELECT * from `hybrid-vertex.jt_towers_v1.candidates_v3`

In [45]:
COMMAND=f"""
gcloud dataflow jobs run {JOB_NAME} \
    --gcs-location gs://dataflow-templates-{REGION_NAME}/{TEMPLATE_VERSION}/Cloud_BigQuery_to_GCS_TensorFlow_Records \
    --region {REGION_NAME} \
    --parameters \
readQuery={READ_QUERY},\
outputDirectory={OUTPUT_DIRECTORY},\
trainingPercentage={TRAINING_PERCENTAGE},\
testingPercentage={TESTING_PERCENTAGE},\
validationPercentage={VALIDATION_PERCENTAGE},\
outputSuffix={OUTPUT_FILENAME_SUFFIX}
"""
print(COMMAND)

gcloud dataflow jobs run create-candidate-tfrs     --gcs-location gs://dataflow-templates-us-central1/latest/Cloud_BigQuery_to_GCS_TensorFlow_Records     --region us-central1     --parameters readQuery=SELECT * from `hybrid-vertex.jt_towers_v1.candidates_v3`,outputDirectory=gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/candidates,trainingPercentage=1,testingPercentage=0,validationPercentage=0,outputSuffix=.tfrecord

In [46]:
! gcloud dataflow jobs run create-candidate-tfrs \
   --gcs-location gs://dataflow-templates-us-central1/latest/Cloud_BigQuery_to_GCS_TensorFlow_Records \
   --region us-central1 \
   --num-workers=20 \
   --parameters readQuery="SELECT * from hybrid-vertex.jt_towers_v1.candidates_v3",outputDirectory="gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/candidates",trainingPercentage=1,testingPercentage=0,validationPercentage=0,outputSuffix=.tfrecord

createTime: '2025-01-29T08:13:12.274502Z'
currentStateTime: '1970-01-01T00:00:00Z'
id: 2025-01-29_00_13_11-11202799578920419846
location: us-central1
name: create-candidate-tfrs
projectId: hybrid-vertex
startTime: '2025-01-29T08:13:12.274502Z'
type: JOB_TYPE_BATCH

In [47]:
! gsutil ls $OUTPUT_DIRECTORY/train
# ! gsutil cp gs://jt-towers-v1-hybrid-vertex-bucket/candidates/train/output-00000-of-00001.tfrecord

gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/candidates/train/output-00000-of-00002.tfrecord
gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/candidates/train/output-00001-of-00002.tfrecord

## Check candidates TF Record file

In [48]:
candidate_features = {
    'target_movie_id': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
    # 'target_movie_genre': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
    'target_movie_year': tf.io.FixedLenFeature(shape=(), dtype=tf.int64),
    'target_movie_title': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
}
def _parse_candidates_fn(example_proto):
    return tf.io.parse_single_example(
        example_proto, candidate_features
    )

CANDIDATE_FILES = [
    "gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/candidates/train/output-00000-of-00002.tfrecord",
    "gs://jt-towers-v1-hybrid-vertex-bucket/data/movielens/m1m_v2/candidates/train/output-00001-of-00002.tfrecord"
]

In [49]:
candidate_dataset = tf.data.TFRecordDataset(CANDIDATE_FILES)

parsed_candidate_dataset = candidate_dataset.map(_parse_candidates_fn)

for x in parsed_candidate_dataset.batch(1).take(1):
    pprint(x)

{'target_movie_id': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b'2522'], dtype=object)>,
 'target_movie_title': <tf.Tensor: shape=(1,), dtype=string, numpy=array([b"Airport '77 (1977)"], dtype=object)>,
 'target_movie_year': <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1977])>}

# gitignore

In [ ]:
# rm -rf `find . -name "*.ipynb_checkpoints" -o -name "*.cpython-310.pyc" -o -name "__pycache__"`

In [14]:
# %%writefile .gitignore
# *.cpython-310.pyc
# *.cpython-37.pyc

# *_checkpoints*
# *__pycache__
# *-checkpoint.py

# # Jupyter Notebook
# .ipynb_checkpoints

# # local data
# src/data/local_data/
# notebooks/local_stash/
# *.csv
# # .gitignore

Overwriting .gitignore

**finished**